items =
{
  "-1": "unset",
  "air": "Air",
  "bow": "Bow",
  "egg": "Egg",
  "ice": "Ice",
  "filled_map": "Map",
  "mud": "Mud",
  "tnt": "TNT",
  "bell": "Bell",
  "bone": "Bone",
  "book": "Book",
  "bowl": "Bowl",
  "cake": "Cake",
  "clay": "Clay",
  "coal": "Coal",
  "dirt": "Dirt",
  "fern": "Fern",
  "fire": "Fire",
  "kelp": "Kelp",
  "lava": "Lava",
  "lead": "Lead",
  "loom": "Loom",
  "mace": "Mace",
  "rail": "Rail",
  "sand": "Sand",
  "snow": "Snow",
  "tuff": "Tuff",
  "anvil": "Anvil",
  "apple": "Apple",
  "arrow": "Arrow",
  "bread": "Bread",
  "brick": "Brick",
  "brush": "Brush",
  "chain": "Chain",
  "chest": "Chest",
  "clock": "Clock",
  "cocoa": "Cocoa",
  "flint": "Flint",
  "glass": "Glass",
  "globe_banner_pattern": "Globe",
  "lever": "Lever",
  "light": "Light",
  "lilac": "Lilac",
  "melon": "Melon",
  "paper": "Paper",
  "peony": "Peony",
  "poppy": "Poppy",
  "sculk": "Sculk",
  "piglin_banner_pattern": "Snout",
  "cooked_beef": "Steak",
  "stick": "Stick",
  "stone": "Stone",
  "sugar": "Sugar",
  "mojang_banner_pattern": "Thing",
  "torch": "Torch",
  "vault": "vault",
  "vine": "Vines",
  "water": "Water",
  "allium": "Allium",
  "azalea": "Azalea",
  "bamboo": "Bamboo",
  "barrel": "Barrel",
  "basalt": "Basalt",
  "beacon": "Beacon",
  "bricks": "Bricks",
  "bucket": "Bucket",
  "bundle": "Bundle",
  "cactus": "Cactus",
  "candle": "Candle",
  "carrot": "Carrot",
  "cobweb": "Cobweb",
  "cookie": "Cookie",
  "elytra": "Elytra",
  "gravel": "Gravel",
  "hopper": "Hopper",
  "ladder": "Ladder",
  "piston": "Piston",
  "podzol": "Podzol",
  "potato": "Potato",
  "potion": "Potion",
  "saddle": "Saddle",
  "shears": "Shears",
  "shield": "Shield",
  "smoker": "Smoker",
  "sponge": "Sponge",
  "string": "String",
  "target": "Target",
  "barrier": "Barrier",
  "bedrock": "Bedrock",
  "beehive": "Beehive",
  "calcite": "Calcite",
  "carrots": "Carrots",
  "compass": "Compass",
  "conduit": "Conduit",
  "crafter": "Crafter",
  "diamond": "Diamond",
  "diorite": "Diorite",
  "dropper": "Dropper",
  "emerald": "Emerald",
  "end_rod": "End Rod",
  "feather": "Feather",
  "furnace": "Furnace",
  "granite": "Granite",
  "ink_sac": "Ink Sac",
  "jukebox": "Jukebox",
  "lantern": "Lantern",
  "leather": "Leather",
  "lectern": "Lectern",
  "oak_log": "Oak Log",
  "pumpkin": "Pumpkin",
  "cod": "Raw Cod",
  "red_bed": "Red Bed",
  "red_dye": "Red Dye",
  "trident": "Trident",
  "andesite": "Andesite",
  "bee_nest": "Bee Nest",
  "beetroot": "Beetroot",
  "blue_bed": "Blue Bed",
  "blue_dye": "Blue Dye",
  "blue_ice": "Blue Ice",
  "campfire": "Campfire",
  "cauldron": "Cauldron",
  "cave_air": "Cave Air",
  "charcoal": "Charcoal",
  "coal_ore": "Coal Ore",
  "crossbow": "Crossbow",
  "cyan_bed": "Cyan Bed",
  "cyan_dye": "Cyan Dye",
  "farmland": "Farmland",
  "gold_ore": "Gold Ore",
  "gray_bed": "Gray Bed",
  "gray_dye": "Gray Dye",
  "hay_block": "Hay Bale",
  "iron_axe": "Iron Axe",
  "iron_hoe": "Iron Hoe",
  "iron_ore": "Iron Ore",
  "lily_pad": "Lily Pad",
  "lime_bed": "Lime Bed",
  "lime_dye": "Lime Dye",
  "minecart": "Minecart",
  "mycelium": "Mycelium",
  "name_tag": "Name Tag",
  "oak_boat": "Oak Boat",
  "oak_door": "Oak Door",
  "oak_sign": "Oak Sign",
  "oak_slab": "Oak Slab",
  "oak_wood": "Oak Wood",
  "observer": "Observer",
  "obsidian": "Obsidian",
  "painting": "Painting",
  "pink_bed": "Pink Bed",
  "pink_dye": "Pink Dye",
  "potatoes": "Potatoes",
  "beef": "Raw Beef",
  "raw_gold": "Raw Gold",
  "raw_iron": "Raw Iron",
  "red_sand": "Red Sand",
  "red_wool": "Red Wool",
  "seagrass": "Seagrass",
  "snowball": "Snowball",
  "spyglass": "Spyglass",
  "tripwire": "Tripwire",
  "void_air": "Void Air",
  "beetroots": "Beetroots",
  "birch_log": "Birch Log",
  "black_bed": "Black Bed",
  "black_dye": "Black Dye",
  "blaze_rod": "Blaze Rod",
  "blue_wool": "Blue Wool",
  "bone_meal": "Bone Meal",
  "bookshelf": "Bookshelf",
  "brown_bed": "Brown Bed",
  "brown_dye": "Brown Dye",
  "music_disc_11": "C418 - 11",
  "music_disc_13": "C418 - 13",
  "clay_ball": "Clay Ball",
  "composter": "Composter",
  "cyan_wool": "Cyan Wool",
  "dandelion": "Dandelion",
  "dead_bush": "Dead Bush",
  "deepslate": "Deepslate",
  "dirt_path": "Dirt Path",
  "dispenser": "Dispenser",
  "map": "Empty Map",
  "end_stone": "End Stone",
  "frogspawn": "Frogspawn",
  "glowstone": "Glowstone",
  "goat_horn": "Goat Horn",
  "gray_wool": "Gray Wool",
  "green_bed": "Green Bed",
  "green_dye": "Green Dye",
  "gunpowder": "Gunpowder",
  "honeycomb": "Honeycomb",
  "iron_bars": "Iron Bars",
  "iron_door": "Iron Door",
  "lime_wool": "Lime Wool",
  "lodestone": "Lodestone",
  "oak_fence": "Oak Fence",
  "pink_wool": "Pink Wool",
  "red_tulip": "Red Tulip",
  "rose_bush": "Rose Bush",
  "sandstone": "Sandstone",
  "slime_ball": "Slimeball",
  "soul_fire": "Soul Fire",
  "soul_sand": "Soul Sand",
  "soul_soil": "Soul Soil",
  "stone_axe": "Stone Axe",
  "stone_hoe": "Stone Hoe",
  "sunflower": "Sunflower",
  "trial_key": "Trial Key",
  "tuff_slab": "Tuff Slab",
  "tuff_wall": "Tuff Wall",
  "white_bed": "White Bed",
  "white_dye": "White Dye",
  "acacia_log": "Acacia Log",
  "birch_boat": "Birch Boat",
  "birch_door": "Birch Door",
  "birch_sign": "Birch Sign",
  "birch_slab": "Birch Slab",
  "birch_wood": "Birch Wood",
  "black_wool": "Black Wool",
  "blackstone": "Blackstone",
  "bone_block": "Bone Block",
  "breeze_rod": "Breeze Rod",
  "brick_slab": "Brick Slab",
  "brick_wall": "Brick Wall",
  "brown_wool": "Brown Wool",
  "music_disc_cat": "C418 - cat",
  "music_disc_far": "C418 - far",
  "cave_vines": "Cave Vines",
  "cherry_log": "Cherry Log",
  "cooked_cod": "Cooked Cod",
  "copper_ore": "Copper Ore",
  "cornflower": "Cornflower",
  "cut_copper": "Cut Copper",
  "dragon_egg": "Dragon Egg",
  "dried_kelp": "Dried Kelp",
  "echo_shard": "Echo Shard",
  "end_portal": "End Portal",
  "fire_coral": "Fire Coral",
  "flower_pot": "Flower Pot",
  "ghast_tear": "Ghast Tear",
  "glass_pane": "Glass Pane",
  "gold_ingot": "Gold Ingot",
  "golden_axe": "Golden Axe",
  "golden_hoe": "Golden Hoe",
  "green_wool": "Green Wool",
  "grindstone": "Grindstone",
  "heavy_core": "Heavy Core",
  "horn_coral": "Horn Coral",
  "iron_boots": "Iron Boots",
  "iron_ingot": "Iron Ingot",
  "iron_sword": "Iron Sword",
  "item_frame": "Item Frame",
  "jungle_log": "Jungle Log",
  "large_fern": "Large Fern",
  "melon_stem": "Melon Stem",
  "moss_block": "Moss Block",
  "mud_bricks": "Mud Bricks",
  "netherrack": "Netherrack",
  "note_block": "Note Block",
  "oak_button": "Oak Button",
  "oak_leaves": "Oak Leaves",
  "oak_planks": "Oak Planks",
  "oak_stairs": "Oak Stairs",
  "orange_bed": "Orange Bed",
  "orange_dye": "Orange Dye",
  "packed_ice": "Packed Ice",
  "packed_mud": "Packed Mud",
  "pink_tulip": "Pink Tulip",
  "prismarine": "Prismarine",
  "pufferfish": "Pufferfish",
  "purple_bed": "Purple Bed",
  "purple_dye": "Purple Dye",
  "raw_copper": "Raw Copper",
  "mutton": "Raw Mutton",
  "rabbit": "Raw Rabbit",
  "salmon": "Raw Salmon",
  "red_banner": "Red Banner",
  "red_candle": "Red Candle",
  "red_carpet": "Red Carpet",
  "sculk_vein": "Sculk Vein",
  "sea_pickle": "Sea Pickle",
  "snow_block": "Snow Block",
  "soul_torch": "Soul Torch",
  "spider_eye": "Spider Eye",
  "spruce_log": "Spruce Log",
  "stone_slab": "Stone Slab",
  "sugar_cane": "Sugar Cane",
  "tall_grass": "Tall Grass",
  "terracotta": "Terracotta",
  "tube_coral": "Tube Coral",
  "turtle_egg": "Turtle Egg",
  "wall_torch": "Wall Torch",
  "wet_sponge": "Wet Sponge",
  "white_wool": "White Wool",
  "wolf_armor": "Wolf Armor",
  "wooden_axe": "Wooden Axe",
  "wooden_hoe": "Wooden Hoe",
  "yellow_bed": "Yellow Bed",
  "yellow_dye": "Yellow Dye",
  "acacia_boat": "Acacia Boat",
  "acacia_door": "Acacia Door",
  "acacia_sign": "Acacia Sign",
  "acacia_slab": "Acacia Slab",
  "acacia_wood": "Acacia Wood",
  "armor_stand": "Armor Stand",
  "azure_bluet": "Azure Bluet",
  "bamboo_door": "Bamboo Door",
  "bamboo_raft": "Bamboo Raft",
  "bamboo_sign": "Bamboo Sign",
  "bamboo_slab": "Bamboo Slab",
  "birch_fence": "Birch Fence",
  "blue_banner": "Blue Banner",
  "blue_candle": "Blue Candle",
  "blue_carpet": "Blue Carpet",
  "blue_orchid": "Blue Orchid",
  "brain_coral": "Brain Coral",
  "music_disc_mall": "C418 - mall",
  "music_disc_stal": "C418 - stal",
  "music_disc_wait": "C418 - wait",
  "music_disc_ward": "C418 - ward",
  "cherry_boat": "Cherry Boat",
  "cherry_door": "Cherry Door",
  "cherry_sign": "Cherry Sign",
  "cherry_slab": "Cherry Slab",
  "cherry_wood": "Cherry Wood",
  "coarse_dirt": "Coarse Dirt",
  "cobblestone": "Cobblestone",
  "cocoa_beans": "Cocoa Beans",
  "copper_bulb": "Copper Bulb",
  "copper_door": "Copper Door",
  "cyan_banner": "Cyan Banner",
  "cyan_candle": "Cyan Candle",
  "cyan_carpet": "Cyan Carpet",
  "debug_stick": "Debug Stick",
  "diamond_axe": "Diamond Axe",
  "diamond_hoe": "Diamond Hoe",
  "diamond_ore": "Diamond Ore",
  "dragon_head": "Dragon Head",
  "emerald_ore": "Emerald Ore",
  "end_crystal": "End Crystal",
  "end_gateway": "End Gateway",
  "ender_chest": "Ender Chest",
  "ender_pearl": "Ender Pearl",
  "fire_charge": "Fire Charge",
  "fishing_rod": "Fishing Rod",
  "frosted_ice": "Frosted Ice",
  "glow_lichen": "Glow Lichen",
  "gold_nugget": "Gold Nugget",
  "grass_block": "Grass Block",
  "gray_banner": "Gray Banner",
  "gray_candle": "Gray Candle",
  "gray_carpet": "Gray Carpet",
  "honey_block": "Honey Block",
  "iron_helmet": "Iron Helmet",
  "iron_nugget": "Iron Nugget",
  "iron_shovel": "Iron Shovel",
  "jungle_boat": "Jungle Boat",
  "jungle_door": "Jungle Door",
  "jungle_sign": "Jungle Sign",
  "jungle_slab": "Jungle Slab",
  "jungle_wood": "Jungle Wood",
  "lava_bucket": "Lava Bucket",
  "leather_helmet": "Leather Cap",
  "lime_banner": "Lime Banner",
  "lime_candle": "Lime Candle",
  "lime_carpet": "Lime Carpet",
  "magenta_bed": "Magenta Bed",
  "magenta_dye": "Magenta Dye",
  "magma_block": "Magma Block",
  "magma_cream": "Magma Cream",
  "melon_seeds": "Melon Seeds",
  "melon_slice": "Melon Slice",
  "milk_bucket": "Milk Bucket",
  "moss_carpet": "Moss Carpet",
  "nether_star": "Nether Star",
  "nether_wart": "Nether Wart",
  "oak_sapling": "Oak Sapling",
  "orange_wool": "Orange Wool",
  "oxeye_daisy": "Oxeye Daisy",
  "piglin_head": "Piglin Head",
  "pink_banner": "Pink Banner",
  "pink_candle": "Pink Candle",
  "pink_carpet": "Pink Carpet",
  "pink_petals": "Pink Petals",
  "piston_head": "Piston Head",
  "pitcher_pod": "Pitcher Pod",
  "player_head": "Player Head",
  "potted_fern": "Potted Fern",
  "powder_snow": "Powder Snow",
  "pumpkin_pie": "Pumpkin Pie",
  "purple_wool": "Purple Wool",
  "purpur_slab": "Purpur Slab",
  "quartz_slab": "Quartz Slab",
  "rabbit_hide": "Rabbit Hide",
  "rabbit_stew": "Rabbit Stew",
  "chicken": "Raw Chicken",
  "rooted_dirt": "Rooted Dirt",
  "scaffolding": "Scaffolding",
  "sea_lantern": "Sea Lantern",
  "short_grass": "Short Grass",
  "shroomlight": "Shroomlight",
  "shulker_box": "Shulker Box",
  "slime_block": "Slime Block",
  "sniffer_egg": "Sniffer Egg",
  "spruce_boat": "Spruce Boat",
  "spruce_door": "Spruce Door",
  "spruce_sign": "Spruce Sign",
  "spruce_slab": "Spruce Slab",
  "spruce_wood": "Spruce Wood",
  "stone_sword": "Stone Sword",
  "stonecutter": "Stonecutter",
  "torchflower": "Torchflower",
  "tuff_bricks": "Tuff Bricks",
  "tuff_stairs": "Tuff Stairs",
  "warped_door": "Warped Door",
  "warped_sign": "Warped Sign",
  "warped_slab": "Warped Slab",
  "warped_stem": "Warped Stem",
  "wheat": "Wheat Crops",
  "wheat_seeds": "Wheat Seeds",
  "white_tulip": "White Tulip",
  "wind_charge": "Wind Charge",
  "wither_rose": "Wither Rose",
  "yellow_wool": "Yellow Wool",
  "zombie_head": "Zombie Head",
  "acacia_fence": "Acacia Fence",
  "baked_potato": "Baked Potato",
  "bamboo_fence": "Bamboo Fence",
  "bamboo_sapling": "Bamboo Shoot",
  "big_dripleaf": "Big Dripleaf",
  "birch_button": "Birch Button",
  "birch_leaves": "Birch Leaves",
  "birch_planks": "Birch Planks",
  "birch_stairs": "Birch Stairs",
  "black_banner": "Black Banner",
  "black_candle": "Black Candle",
  "black_carpet": "Black Carpet",
  "blaze_powder": "Blaze Powder",
  "brick_stairs": "Brick Stairs",
  "brown_banner": "Brown Banner",
  "brown_candle": "Brown Candle",
  "brown_carpet": "Brown Carpet",
  "bubble_coral": "Bubble Coral",
  "music_disc_chirp": "C418 - chirp",
  "music_disc_strad": "C418 - strad",
  "cherry_fence": "Cherry Fence",
  "chorus_fruit": "Chorus Fruit",
  "chorus_plant": "Chorus Plant",
  "copper_grate": "Copper Grate",
  "copper_ingot": "Copper Ingot",
  "creeper_head": "Creeper Head",
  "crimson_door": "Crimson Door",
  "crimson_sign": "Crimson Sign",
  "crimson_slab": "Crimson Slab",
  "crimson_stem": "Crimson Stem",
  "dark_oak_log": "Dark Oak Log",
  "diorite_slab": "Diorite Slab",
  "diorite_wall": "Diorite Wall",
  "ender_eye": "Eye of Ender",
  "glass_bottle": "Glass Bottle",
  "glow_berries": "Glow Berries",
  "glow_ink_sac": "Glow Ink Sac",
  "golden_apple": "Golden Apple",
  "golden_boots": "Golden Boots",
  "golden_sword": "Golden Sword",
  "granite_slab": "Granite Slab",
  "granite_wall": "Granite Wall",
  "green_banner": "Green Banner",
  "green_candle": "Green Candle",
  "green_carpet": "Green Carpet",
  "honey_bottle": "Honey Bottle",
  "iron_pickaxe": "Iron Pickaxe",
  "jigsaw": "Jigsaw Block",
  "jungle_fence": "Jungle Fence",
  "lapis_lazuli": "Lapis Lazuli",
  "magenta_wool": "Magenta Wool",
  "mangrove_log": "Mangrove Log",
  "nether_brick": "Nether Brick",
  "oak_trapdoor": "Oak Trapdoor",
  "orange_tulip": "Orange Tulip",
  "pitcher_crop": "Pitcher Crop",
  "potted_poppy": "Potted Poppy",
  "powered_rail": "Powered Rail",
  "pumpkin_stem": "Pumpkin Stem",
  "purpur_block": "Purpur Block",
  "porkchop": "Raw Porkchop",
  "red_concrete": "Red Concrete",
  "red_mushroom": "Red Mushroom",
  "redstone_ore": "Redstone Ore",
  "rotten_flesh": "Rotten Flesh",
  "sculk_sensor": "Sculk Sensor",
  "skull_banner_pattern": "Skull Charge",
  "smooth_stone": "Smooth Stone",
  "soul_lantern": "Soul Lantern",
  "spruce_fence": "Spruce Fence",
  "stone_bricks": "Stone Bricks",
  "stone_button": "Stone Button",
  "stone_shovel": "Stone Shovel",
  "stone_stairs": "Stone Stairs",
  "tinted_glass": "Tinted Glass",
  "tipped_arrow": "Tipped Arrow",
  "turtle_scute": "Turtle Scute",
  "turtle_helmet": "Turtle Shell",
  "warped_fence": "Warped Fence",
  "warped_roots": "Warped Roots",
  "water_bucket": "Water Bucket",
  "white_banner": "White Banner",
  "white_candle": "White Candle",
  "white_carpet": "White Carpet",
  "wooden_sword": "Wooden Sword",
  "written_book": "Written Book",
  "acacia_button": "Acacia Button",
  "acacia_leaves": "Acacia Leaves",
  "acacia_planks": "Acacia Planks",
  "acacia_stairs": "Acacia Stairs",
  "andesite_slab": "Andesite Slab",
  "andesite_wall": "Andesite Wall",
  "azalea_leaves": "Azalea Leaves",
  "bamboo_button": "Bamboo Button",
  "bamboo_mosaic": "Bamboo Mosaic",
  "bamboo_planks": "Bamboo Planks",
  "bamboo_stairs": "Bamboo Stairs",
  "bat_spawn_egg": "Bat Spawn Egg",
  "bee_spawn_egg": "Bee Spawn Egg",
  "beetroot_soup": "Beetroot Soup",
  "birch_sapling": "Birch Sapling",
  "blast_furnace": "Blast Furnace",
  "coal_block": "Block of Coal",
  "gold_block": "Block of Gold",
  "iron_block": "Block of Iron",
  "blue_concrete": "Blue Concrete",
  "brewing_stand": "Brewing Stand",
  "cod_bucket": "Bucket of Cod",
  "music_disc_blocks": "C418 - blocks",
  "cat_spawn_egg": "Cat Spawn Egg",
  "cherry_button": "Cherry Button",
  "cherry_leaves": "Cherry Leaves",
  "cherry_planks": "Cherry Planks",
  "cherry_stairs": "Cherry Stairs",
  "chipped_anvil": "Chipped Anvil",
  "chiseled_tuff": "Chiseled Tuff",
  "chorus_flower": "Chorus Flower",
  "cod_spawn_egg": "Cod Spawn Egg",
  "command_block": "Command Block",
  "cooked_mutton": "Cooked Mutton",
  "cooked_rabbit": "Cooked Rabbit",
  "cooked_salmon": "Cooked Salmon",
  "cow_spawn_egg": "Cow Spawn Egg",
  "crimson_fence": "Crimson Fence",
  "crimson_roots": "Crimson Roots",
  "cut_sandstone": "Cut Sandstone",
  "cyan_concrete": "Cyan Concrete",
  "damaged_anvil": "Damaged Anvil",
  "dark_oak_boat": "Dark Oak Boat",
  "dark_oak_door": "Dark Oak Door",
  "dark_oak_sign": "Dark Oak Sign",
  "dark_oak_slab": "Dark Oak Slab",
  "dark_oak_wood": "Dark Oak Wood",
  "decorated_pot": "Decorated Pot",
  "detector_rail": "Detector Rail",
  "diamond_boots": "Diamond Boots",
  "diamond_sword": "Diamond Sword",
  "disc_fragment_5": "Disc Fragment",
  "firework_star": "Firework Star",
  "flower_banner_pattern": "Flower Charge",
  "fox_spawn_egg": "Fox Spawn Egg",
  "golden_carrot": "Golden Carrot",
  "golden_helmet": "Golden Helmet",
  "golden_shovel": "Golden Shovel",
  "gray_concrete": "Gray Concrete",
  "hanging_roots": "Hanging Roots",
  "iron_leggings": "Iron Leggings",
  "iron_trapdoor": "Iron Trapdoor",
  "jungle_button": "Jungle Button",
  "jungle_leaves": "Jungle Leaves",
  "jungle_planks": "Jungle Planks",
  "jungle_stairs": "Jungle Stairs",
  "lava_cauldron": "Lava Cauldron",
  "leather_boots": "Leather Boots",
  "leather_leggings": "Leather Pants",
  "leather_chestplate": "Leather Tunic",
  "lightning_rod": "Lightning Rod",
  "lime_concrete": "Lime Concrete",
  "mangrove_boat": "Mangrove Boat",
  "mangrove_door": "Mangrove Door",
  "mangrove_sign": "Mangrove Sign",
  "mangrove_slab": "Mangrove Slab",
  "mangrove_wood": "Mangrove Wood",
  "moving_piston": "Moving Piston",
  "mushroom_stem": "Mushroom Stem",
  "mushroom_stew": "Mushroom Stew",
  "nether_bricks": "Nether Bricks",
  "nether_portal": "Nether Portal",
  "quartz": "Nether Quartz",
  "netherite_axe": "Netherite Axe",
  "netherite_hoe": "Netherite Hoe",
  "oak_wall_sign": "Oak Wall Sign",
  "orange_banner": "Orange Banner",
  "orange_candle": "Orange Candle",
  "orange_carpet": "Orange Carpet",
  "pig_spawn_egg": "Pig Spawn Egg",
  "pink_concrete": "Pink Concrete",
  "pitcher_plant": "Pitcher Plant",
  "polished_tuff": "Polished Tuff",
  "potted_allium": "Potted Allium",
  "potted_azalea_bush": "Potted Azalea",
  "potted_bamboo": "Potted Bamboo",
  "potted_cactus": "Potted Cactus",
  "pumpkin_seeds": "Pumpkin Seeds",
  "purple_banner": "Purple Banner",
  "purple_candle": "Purple Candle",
  "purple_carpet": "Purple Carpet",
  "purpur_pillar": "Purpur Pillar",
  "purpur_stairs": "Purpur Stairs",
  "quartz_bricks": "Quartz Bricks",
  "quartz_pillar": "Quartz Pillar",
  "quartz_stairs": "Quartz Stairs",
  "rabbit_foot": "Rabbit's Foot",
  "red_sandstone": "Red Sandstone",
  "redstone": "Redstone Dust",
  "redstone_lamp": "Redstone Lamp",
  "redstone_wire": "Redstone Wire",
  "shulker_shell": "Shulker Shell",
  "smooth_basalt": "Smooth Basalt",
  "soul_campfire": "Soul Campfire",
  "splash_potion": "Splash Potion",
  "spore_blossom": "Spore Blossom",
  "spruce_button": "Spruce Button",
  "spruce_leaves": "Spruce Leaves",
  "spruce_planks": "Spruce Planks",
  "spruce_stairs": "Spruce Stairs",
  "sticky_piston": "Sticky Piston",
  "stone_pickaxe": "Stone Pickaxe",
  "sweet_berries": "Sweet Berries",
  "trapped_chest": "Trapped Chest",
  "trial_spawner": "Trial Spawner",
  "tripwire_hook": "Tripwire Hook",
  "tropical_fish": "Tropical Fish",
  "vex_spawn_egg": "Vex Spawn Egg",
  "warped_button": "Warped Button",
  "warped_fungus": "Warped Fungus",
  "warped_hyphae": "Warped Hyphae",
  "warped_nylium": "Warped Nylium",
  "warped_planks": "Warped Planks",
  "warped_stairs": "Warped Stairs",
  "weeping_vines": "Weeping Vines",
  "wooden_shovel": "Wooden Shovel",
  "yellow_banner": "Yellow Banner",
  "yellow_candle": "Yellow Candle",
  "yellow_carpet": "Yellow Carpet",
  "acacia_sapling": "Acacia Sapling",
  "activator_rail": "Activator Rail",
  "amethyst_shard": "Amethyst Shard",
  "ancient_debris": "Ancient Debris",
  "beetroot_seeds": "Beetroot Seeds",
  "birch_trapdoor": "Birch Trapdoor",
  "black_concrete": "Black Concrete",
  "writable_book": "Book and Quill",
  "brown_concrete": "Brown Concrete",
  "brown_mushroom": "Brown Mushroom",
  "music_disc_mellohi": "C418 - mellohi",
  "carved_pumpkin": "Carved Pumpkin",
  "cherry_sapling": "Cherry Sapling",
  "cooked_chicken": "Cooked Chicken",
  "crafting_table": "Crafting Table",
  "creeper_banner_pattern": "Creeper Charge",
  "crimson_button": "Crimson Button",
  "crimson_fungus": "Crimson Fungus",
  "crimson_hyphae": "Crimson Hyphae",
  "crimson_nylium": "Crimson Nylium",
  "crimson_planks": "Crimson Planks",
  "crimson_stairs": "Crimson Stairs",
  "dark_oak_fence": "Dark Oak Fence",
  "diamond_helmet": "Diamond Helmet",
  "diamond_shovel": "Diamond Shovel",
  "diorite_stairs": "Diorite Stairs",
  "enchanted_book": "Enchanted Book",
  "exposed_copper": "Exposed Copper",
  "fire_coral_fan": "Fire Coral Fan",
  "frog_spawn_egg": "Frog Spawn Egg",
  "glowstone_dust": "Glowstone Dust",
  "goat_spawn_egg": "Goat Spawn Egg",
  "golden_pickaxe": "Golden Pickaxe",
  "granite_stairs": "Granite Stairs",
  "green_concrete": "Green Concrete",
  "horn_coral_fan": "Horn Coral Fan",
  "husk_spawn_egg": "Husk Spawn Egg",
  "infested_stone": "Infested Stone",
  "jack_o_lantern": "Jack o'Lantern",
  "jungle_sapling": "Jungle Sapling",
  "knowledge_book": "Knowledge Book",
  "light_blue_bed": "Light Blue Bed",
  "light_blue_dye": "Light Blue Dye",
  "light_gray_bed": "Light Gray Bed",
  "light_gray_dye": "Light Gray Dye",
  "magenta_banner": "Magenta Banner",
  "magenta_candle": "Magenta Candle",
  "magenta_carpet": "Magenta Carpet",
  "mangrove_fence": "Mangrove Fence",
  "mangrove_roots": "Mangrove Roots",
  "mud_brick_slab": "Mud Brick Slab",
  "mud_brick_wall": "Mud Brick Wall",
  "mule_spawn_egg": "Mule Spawn Egg",
  "nautilus_shell": "Nautilus Shell",
  "nether_sprouts": "Nether Sprouts",
  "oak_fence_gate": "Oak Fence Gate",
  "ominous_bottle": "Ominous Bottle",
  "red_terracotta": "Red Terracotta",
  "redstone_torch": "Redstone Torch",
  "respawn_anchor": "Respawn Anchor",
  "sandstone_slab": "Sandstone Slab",
  "sandstone_wall": "Sandstone Wall",
  "sculk_catalyst": "Sculk Catalyst",
  "sculk_shrieker": "Sculk Shrieker",
  "skeleton_skull": "Skeleton Skull",
  "small_dripleaf": "Small Dripleaf",
  "smithing_table": "Smithing Table",
  "spectral_arrow": "Spectral Arrow",
  "spruce_sapling": "Spruce Sapling",
  "structure_void": "Structure Void",
  "tube_coral_fan": "Tube Coral Fan",
  "twisting_vines": "Twisting Vines",
  "water_cauldron": "Water Cauldron",
  "white_concrete": "White Concrete",
  "wolf_spawn_egg": "Wolf Spawn Egg",
  "wooden_pickaxe": "Wooden Pickaxe",
  "acacia_trapdoor": "Acacia Trapdoor",
  "allay_spawn_egg": "Allay Spawn Egg",
  "andesite_stairs": "Andesite Stairs",
  "armadillo_scute": "Armadillo Scute",
  "bamboo_trapdoor": "Bamboo Trapdoor",
  "birch_wall_sign": "Birch Wall Sign",
  "blackstone_slab": "Blackstone Slab",
  "blackstone_wall": "Blackstone Wall",
  "blaze_spawn_egg": "Blaze Spawn Egg",
  "bamboo_block": "Block of Bamboo",
  "copper_block": "Block of Copper",
  "quartz_block": "Block of Quartz",
  "blue_terracotta": "Blue Terracotta",
  "brain_coral_fan": "Brain Coral Fan",
  "camel_spawn_egg": "Camel Spawn Egg",
  "chainmail_boots": "Chainmail Boots",
  "cherry_trapdoor": "Cherry Trapdoor",
  "chiseled_copper": "Chiseled Copper",
  "cooked_porkchop": "Cooked Porkchop",
  "copper_trapdoor": "Copper Trapdoor",
  "crying_obsidian": "Crying Obsidian",
  "cut_copper_slab": "Cut Copper Slab",
  "cyan_terracotta": "Cyan Terracotta",
  "dark_oak_button": "Dark Oak Button",
  "dark_oak_leaves": "Dark Oak Leaves",
  "dark_oak_planks": "Dark Oak Planks",
  "dark_oak_stairs": "Dark Oak Stairs",
  "dark_prismarine": "Dark Prismarine",
  "dead_fire_coral": "Dead Fire Coral",
  "dead_horn_coral": "Dead Horn Coral",
  "dead_tube_coral": "Dead Tube Coral",
  "deepslate_tiles": "Deepslate Tiles",
  "diamond_pickaxe": "Diamond Pickaxe",
  "dragon_breath": "Dragon's Breath",
  "dripstone_block": "Dripstone Block",
  "firework_rocket": "Firework Rocket",
  "fletching_table": "Fletching Table",
  "flint_and_steel": "Flint and Steel",
  "ghast_spawn_egg": "Ghast Spawn Egg",
  "glow_item_frame": "Glow Item Frame",
  "golden_leggings": "Golden Leggings",
  "gray_terracotta": "Gray Terracotta",
  "honeycomb_block": "Honeycomb Block",
  "horse_spawn_egg": "Horse Spawn Egg",
  "iron_chestplate": "Iron Chestplate",
  "jungle_trapdoor": "Jungle Trapdoor",
  "light_blue_wool": "Light Blue Wool",
  "light_gray_wool": "Light Gray Wool",
  "lime_terracotta": "Lime Terracotta",
  "llama_spawn_egg": "Llama Spawn Egg",
  "mangrove_button": "Mangrove Button",
  "mangrove_leaves": "Mangrove Leaves",
  "mangrove_planks": "Mangrove Planks",
  "mangrove_stairs": "Mangrove Stairs",
  "spawner": "Monster Spawner",
  "nether_gold_ore": "Nether Gold Ore",
  "netherite_boots": "Netherite Boots",
  "netherite_ingot": "Netherite Ingot",
  "netherite_scrap": "Netherite Scrap",
  "netherite_sword": "Netherite Sword",
  "ochre_froglight": "Ochre Froglight",
  "orange_concrete": "Orange Concrete",
  "oxidized_copper": "Oxidized Copper",
  "panda_spawn_egg": "Panda Spawn Egg",
  "pink_terracotta": "Pink Terracotta",
  "polished_basalt": "Polished Basalt",
  "prismarine_slab": "Prismarine Slab",
  "prismarine_wall": "Prismarine Wall",
  "purple_concrete": "Purple Concrete",
  "red_shulker_box": "Red Shulker Box",
  "sheep_spawn_egg": "Sheep Spawn Egg",
  "slime_spawn_egg": "Slime Spawn Egg",
  "soul_wall_torch": "Soul Wall Torch",
  "spruce_trapdoor": "Spruce Trapdoor",
  "squid_spawn_egg": "Squid Spawn Egg",
  "stray_spawn_egg": "Stray Spawn Egg",
  "structure_block": "Structure Block",
  "suspicious_sand": "Suspicious Sand",
  "suspicious_stew": "Suspicious Stew",
  "tuff_brick_slab": "Tuff Brick Slab",
  "tuff_brick_wall": "Tuff Brick Wall",
  "warped_trapdoor": "Warped Trapdoor",
  "witch_spawn_egg": "Witch Spawn Egg",
  "yellow_concrete": "Yellow Concrete",
  "acacia_wall_sign": "Acacia Wall Sign",
  "amethyst_cluster": "Amethyst Cluster",
  "bamboo_wall_sign": "Bamboo Wall Sign",
  "birch_fence_gate": "Birch Fence Gate",
  "black_terracotta": "Black Terracotta",
  "diamond_block": "Block of Diamond",
  "emerald_block": "Block of Emerald",
  "blue_shulker_box": "Blue Shulker Box",
  "bogged_spawn_egg": "Bogged Spawn Egg",
  "breeze_spawn_egg": "Breeze Spawn Egg",
  "brown_terracotta": "Brown Terracotta",
  "bubble_coral_fan": "Bubble Coral Fan",
  "salmon_bucket": "Bucket of Salmon",
  "budding_amethyst": "Budding Amethyst",
  "candle_cake": "Cake with Candle",
  "cave_vines_plant": "Cave Vines Plant",
  "chainmail_helmet": "Chainmail Helmet",
  "cherry_wall_sign": "Cherry Wall Sign",
  "cobblestone_slab": "Cobblestone Slab",
  "cobblestone_wall": "Cobblestone Wall",
  "crimson_trapdoor": "Crimson Trapdoor",
  "cyan_shulker_box": "Cyan Shulker Box",
  "dark_oak_sapling": "Dark Oak Sapling",
  "dead_brain_coral": "Dead Brain Coral",
  "deepslate_bricks": "Deepslate Bricks",
  "diamond_leggings": "Diamond Leggings",
  "donkey_spawn_egg": "Donkey Spawn Egg",
  "dragon_wall_head": "Dragon Wall Head",
  "dried_kelp_block": "Dried Kelp Block",
  "enchanting_table": "Enchanting Table",
  "end_portal_frame": "End Portal Frame",
  "end_stone_bricks": "End Stone Bricks",
  "evoker_spawn_egg": "Evoker Spawn Egg",
  "fire_coral_block": "Fire Coral Block",
  "flowering_azalea": "Flowering Azalea",
  "gray_shulker_box": "Gray Shulker Box",
  "green_terracotta": "Green Terracotta",
  "heart_of_the_sea": "Heart of the Sea",
  "hoglin_spawn_egg": "Hoglin Spawn Egg",
  "horn_coral_block": "Horn Coral Block",
  "iron_horse_armor": "Iron Horse Armor",
  "jungle_wall_sign": "Jungle Wall Sign",
  "lapis_ore": "Lapis Lazuli Ore",
  "lime_shulker_box": "Lime Shulker Box",
  "lingering_potion": "Lingering Potion",
  "magenta_concrete": "Magenta Concrete",
  "mud_brick_stairs": "Mud Brick Stairs",
  "netherite_helmet": "Netherite Helmet",
  "netherite_shovel": "Netherite Shovel",
  "oak_hanging_sign": "Oak Hanging Sign",
  "ocelot_spawn_egg": "Ocelot Spawn Egg",
  "parrot_spawn_egg": "Parrot Spawn Egg",
  "phantom_membrane": "Phantom Membrane",
  "piglin_spawn_egg": "Piglin Spawn Egg",
  "piglin_wall_head": "Piglin Wall Head",
  "pink_shulker_box": "Pink Shulker Box",
  "player_wall_head": "Player Wall Head",
  "poisonous_potato": "Poisonous Potato",
  "polished_diorite": "Polished Diorite",
  "polished_granite": "Polished Granite",
  "potted_dandelion": "Potted Dandelion",
  "potted_dead_bush": "Potted Dead Bush",
  "potted_red_tulip": "Potted Red Tulip",
  "prismarine_shard": "Prismarine Shard",
  "rabbit_spawn_egg": "Rabbit Spawn Egg",
  "recovery_compass": "Recovery Compass",
  "salmon_spawn_egg": "Salmon Spawn Egg",
  "music_disc_5": "Samuel Åberg - 5",
  "sandstone_stairs": "Sandstone Stairs",
  "smooth_sandstone": "Smooth Sandstone",
  "spider_spawn_egg": "Spider Spawn Egg",
  "spruce_wall_sign": "Spruce Wall Sign",
  "stone_brick_slab": "Stone Brick Slab",
  "stone_brick_wall": "Stone Brick Wall",
  "stripped_oak_log": "Stripped Oak Log",
  "sweet_berry_bush": "Sweet Berry Bush",
  "torchflower_crop": "Torchflower Crop",
  "totem_of_undying": "Totem of Undying",
  "tube_coral_block": "Tube Coral Block",
  "turtle_spawn_egg": "Turtle Spawn Egg",
  "warden_spawn_egg": "Warden Spawn Egg",
  "warped_wall_sign": "Warped Wall Sign",
  "waxed_cut_copper": "Waxed Cut Copper",
  "weathered_copper": "Weathered Copper",
  "white_terracotta": "White Terracotta",
  "wither_spawn_egg": "Wither Spawn Egg",
  "zoglin_spawn_egg": "Zoglin Spawn Egg",
  "zombie_spawn_egg": "Zombie Spawn Egg",
  "zombie_wall_head": "Zombie Wall Head",
  "acacia_fence_gate": "Acacia Fence Gate",
  "axolotl_spawn_egg": "Axolotl Spawn Egg",
  "bamboo_fence_gate": "Bamboo Fence Gate",
  "big_dripleaf_stem": "Big Dripleaf Stem",
  "black_shulker_box": "Black Shulker Box",
  "blackstone_stairs": "Blackstone Stairs",
  "amethyst_block": "Block of Amethyst",
  "raw_gold_block": "Block of Raw Gold",
  "raw_iron_block": "Block of Raw Iron",
  "redstone_block": "Block of Redstone",
  "brain_coral_block": "Brain Coral Block",
  "brown_shulker_box": "Brown Shulker Box",
  "axolotl_bucket": "Bucket of Axolotl",
  "tadpole_bucket": "Bucket of Tadpole",
  "carrot_on_a_stick": "Carrot on a Stick",
  "cartography_table": "Cartography Table",
  "cherry_fence_gate": "Cherry Fence Gate",
  "chicken_spawn_egg": "Chicken Spawn Egg",
  "cobbled_deepslate": "Cobbled Deepslate",
  "creeper_spawn_egg": "Creeper Spawn Egg",
  "creeper_wall_head": "Creeper Wall Head",
  "crimson_wall_sign": "Crimson Wall Sign",
  "cut_copper_stairs": "Cut Copper Stairs",
  "cut_red_sandstone": "Cut Red Sandstone",
  "dark_oak_trapdoor": "Dark Oak Trapdoor",
  "daylight_detector": "Daylight Detector",
  "dead_bubble_coral": "Dead Bubble Coral",
  "dolphin_spawn_egg": "Dolphin Spawn Egg",
  "drowned_spawn_egg": "Drowned Spawn Egg",
  "gilded_blackstone": "Gilded Blackstone",
  "golden_chestplate": "Golden Chestplate",
  "green_shulker_box": "Green Shulker Box",
  "jungle_fence_gate": "Jungle Fence Gate",
  "light_blue_banner": "Light Blue Banner",
  "light_blue_candle": "Light Blue Candle",
  "light_blue_carpet": "Light Blue Carpet",
  "light_gray_banner": "Light Gray Banner",
  "light_gray_candle": "Light Gray Candle",
  "light_gray_carpet": "Light Gray Carpet",
  "mangrove_trapdoor": "Mangrove Trapdoor",
  "tnt_minecart": "Minecart with TNT",
  "mossy_cobblestone": "Mossy Cobblestone",
  "nether_brick_slab": "Nether Brick Slab",
  "nether_brick_wall": "Nether Brick Wall",
  "nether_quartz_ore": "Nether Quartz Ore",
  "nether_wart_block": "Nether Wart Block",
  "netherite_pickaxe": "Netherite Pickaxe",
  "ominous_trial_key": "Ominous Trial Key",
  "orange_terracotta": "Orange Terracotta",
  "phantom_spawn_egg": "Phantom Spawn Egg",
  "pointed_dripstone": "Pointed Dripstone",
  "polished_andesite": "Polished Andesite",
  "potted_pink_tulip": "Potted Pink Tulip",
  "prismarine_bricks": "Prismarine Bricks",
  "prismarine_stairs": "Prismarine Stairs",
  "purple_terracotta": "Purple Terracotta",
  "ravager_spawn_egg": "Ravager Spawn Egg",
  "red_wall_banner": "Red Banner (Wall)",
  "red_nether_bricks": "Red Nether Bricks",
  "red_stained_glass": "Red Stained Glass",
  "repeater": "Redstone Repeater",
  "shulker_spawn_egg": "Shulker Spawn Egg",
  "smooth_stone_slab": "Smooth Stone Slab",
  "sniffer_spawn_egg": "Sniffer Spawn Egg",
  "spruce_fence_gate": "Spruce Fence Gate",
  "strider_spawn_egg": "Strider Spawn Egg",
  "stripped_oak_wood": "Stripped Oak Wood",
  "suspicious_gravel": "Suspicious Gravel",
  "tadpole_spawn_egg": "Tadpole Spawn Egg",
  "torchflower_seeds": "Torchflower Seeds",
  "tuff_brick_stairs": "Tuff Brick Stairs",
  "verdant_froglight": "Verdant Froglight",
  "warped_fence_gate": "Warped Fence Gate",
  "warped_wart_block": "Warped Wart Block",
  "waxed_copper_bulb": "Waxed Copper Bulb",
  "waxed_copper_door": "Waxed Copper Door",
  "white_shulker_box": "White Shulker Box",
  "yellow_terracotta": "Yellow Terracotta",
  "bamboo_mosaic_slab": "Bamboo Mosaic Slab",
  "birch_hanging_sign": "Birch Hanging Sign",
  "netherite_block": "Block of Netherite",
  "blue_wall_banner": "Blue Banner (Wall)",
  "blue_stained_glass": "Blue Stained Glass",
  "bubble_coral_block": "Bubble Coral Block",
  "burn_pottery_sherd": "Burn Pottery Sherd",
  "chainmail_leggings": "Chainmail Leggings",
  "chiseled_bookshelf": "Chiseled Bookshelf",
  "chiseled_deepslate": "Chiseled Deepslate",
  "chiseled_sandstone": "Chiseled Sandstone",
  "cobblestone_stairs": "Cobblestone Stairs",
  "crimson_fence_gate": "Crimson Fence Gate",
  "cut_sandstone_slab": "Cut Sandstone Slab",
  "cyan_wall_banner": "Cyan Banner (Wall)",
  "cyan_stained_glass": "Cyan Stained Glass",
  "dark_oak_wall_sign": "Dark Oak Wall Sign",
  "deepslate_coal_ore": "Deepslate Coal Ore",
  "deepslate_gold_ore": "Deepslate Gold Ore",
  "deepslate_iron_ore": "Deepslate Iron Ore",
  "diamond_chestplate": "Diamond Chestplate",
  "enderman_spawn_egg": "Enderman Spawn Egg",
  "exposed_cut_copper": "Exposed Cut Copper",
  "flow_pottery_sherd": "Flow Pottery Sherd",
  "golden_horse_armor": "Golden Horse Armor",
  "gray_wall_banner": "Gray Banner (Wall)",
  "gray_stained_glass": "Gray Stained Glass",
  "guardian_spawn_egg": "Guardian Spawn Egg",
  "howl_pottery_sherd": "Howl Pottery Sherd",
  "infested_deepslate": "Infested Deepslate",
  "large_amethyst_bud": "Large Amethyst Bud",
  "lily_of_the_valley": "Lily of the Valley",
  "lime_wall_banner": "Lime Banner (Wall)",
  "lime_stained_glass": "Lime Stained Glass",
  "magenta_terracotta": "Magenta Terracotta",
  "mangrove_propagule": "Mangrove Propagule",
  "mangrove_wall_sign": "Mangrove Wall Sign",
  "mossy_stone_bricks": "Mossy Stone Bricks",
  "music_disc_creator": "Music Disc Creator",
  "nether_brick_fence": "Nether Brick Fence",
  "netherite_leggings": "Netherite Leggings",
  "oak_pressure_plate": "Oak Pressure Plate",
  "orange_shulker_box": "Orange Shulker Box",
  "petrified_oak_slab": "Petrified Oak Slab",
  "pillager_spawn_egg": "Pillager Spawn Egg",
  "pink_wall_banner": "Pink Banner (Wall)",
  "pink_stained_glass": "Pink Stained Glass",
  "polished_deepslate": "Polished Deepslate",
  "polished_tuff_slab": "Polished Tuff Slab",
  "polished_tuff_wall": "Polished Tuff Wall",
  "potted_azure_bluet": "Potted Azure Bluet",
  "potted_blue_orchid": "Potted Blue Orchid",
  "potted_oak_sapling": "Potted Oak Sapling",
  "potted_oxeye_daisy": "Potted Oxeye Daisy",
  "potted_white_tulip": "Potted White Tulip",
  "powder_snow_bucket": "Powder Snow Bucket",
  "purple_shulker_box": "Purple Shulker Box",
  "red_mushroom_block": "Red Mushroom Block",
  "red_sandstone_slab": "Red Sandstone Slab",
  "red_sandstone_wall": "Red Sandstone Wall",
  "skeleton_spawn_egg": "Skeleton Spawn Egg",
  "small_amethyst_bud": "Small Amethyst Bud",
  "smooth_quartz_slab": "Smooth Quartz Slab",
  "stone_brick_stairs": "Stone Brick Stairs",
  "stripped_birch_log": "Stripped Birch Log",
  "villager_spawn_egg": "Villager Spawn Egg",
  "waxed_copper_grate": "Waxed Copper Grate",
  "yellow_shulker_box": "Yellow Shulker Box",
  "acacia_hanging_sign": "Acacia Hanging Sign",
  "armadillo_spawn_egg": "Armadillo Spawn Egg",
  "attached_melon_stem": "Attached Melon Stem",
  "bamboo_hanging_sign": "Bamboo Hanging Sign",
  "black_wall_banner": "Black Banner (Wall)",
  "black_stained_glass": "Black Stained Glass",
  "blade_pottery_sherd": "Blade Pottery Sherd",
  "raw_copper_block": "Block of Raw Copper",
  "brown_wall_banner": "Brown Banner (Wall)",
  "brown_stained_glass": "Brown Stained Glass",
  "chain_command_block": "Chain Command Block",
  "cherry_hanging_sign": "Cherry Hanging Sign",
  "dark_oak_fence_gate": "Dark Oak Fence Gate",
  "dead_fire_coral_fan": "Dead Fire Coral Fan",
  "dead_horn_coral_fan": "Dead Horn Coral Fan",
  "dead_tube_coral_fan": "Dead Tube Coral Fan",
  "deepslate_tile_slab": "Deepslate Tile Slab",
  "deepslate_tile_wall": "Deepslate Tile Wall",
  "diamond_horse_armor": "Diamond Horse Armor",
  "endermite_spawn_egg": "Endermite Spawn Egg",
  "exposed_copper_bulb": "Exposed Copper Bulb",
  "exposed_copper_door": "Exposed Copper Door",
  "fire_coral_wall_fan": "Fire Coral Wall Fan",
  "flow_banner_pattern": "Flow Banner Pattern",
  "green_wall_banner": "Green Banner (Wall)",
  "green_stained_glass": "Green Stained Glass",
  "heart_pottery_sherd": "Heart Pottery Sherd",
  "horn_coral_wall_fan": "Horn Coral Wall Fan",
  "jungle_hanging_sign": "Jungle Hanging Sign",
  "leather_horse_armor": "Leather Horse Armor",
  "light_blue_concrete": "Light Blue Concrete",
  "light_gray_concrete": "Light Gray Concrete",
  "magenta_shulker_box": "Magenta Shulker Box",
  "mangrove_fence_gate": "Mangrove Fence Gate",
  "medium_amethyst_bud": "Medium Amethyst Bud",
  "chest_minecart": "Minecart with Chest",
  "miner_pottery_sherd": "Miner Pottery Sherd",
  "mooshroom_spawn_egg": "Mooshroom Spawn Egg",
  "nether_brick_stairs": "Nether Brick Stairs",
  "oak_chest_boat": "Oak Boat with Chest",
  "oxidized_cut_copper": "Oxidized Cut Copper",
  "polished_blackstone": "Polished Blackstone",
  "popped_chorus_fruit": "Popped Chorus Fruit",
  "potted_orange_tulip": "Potted Orange Tulip",
  "potted_red_mushroom": "Potted Red Mushroom",
  "potted_warped_roots": "Potted Warped Roots",
  "prismarine_crystals": "Prismarine Crystals",
  "prize_pottery_sherd": "Prize Pottery Sherd",
  "red_concrete_powder": "Red Concrete Powder",
  "comparator": "Redstone Comparator",
  "redstone_wall_torch": "Redstone Wall Torch",
  "sheaf_pottery_sherd": "Sheaf Pottery Sherd",
  "skeleton_wall_skull": "Skeleton Wall Skull",
  "skull_pottery_sherd": "Skull Pottery Sherd",
  "smooth_quartz": "Smooth Quartz Block",
  "snort_pottery_sherd": "Snort Pottery Sherd",
  "spruce_hanging_sign": "Spruce Hanging Sign",
  "stripped_acacia_log": "Stripped Acacia Log",
  "stripped_birch_wood": "Stripped Birch Wood",
  "stripped_cherry_log": "Stripped Cherry Log",
  "stripped_jungle_log": "Stripped Jungle Log",
  "stripped_spruce_log": "Stripped Spruce Log",
  "tube_coral_wall_fan": "Tube Coral Wall Fan",
  "warped_hanging_sign": "Warped Hanging Sign",
  "weeping_vines_plant": "Weeping Vines Plant",
  "white_wall_banner": "White Banner (Wall)",
  "white_stained_glass": "White Stained Glass",
  "music_disc_relic": "Aaron Cherof - Relic",
  "angler_pottery_sherd": "Angler Pottery Sherd",
  "archer_pottery_sherd": "Archer Pottery Sherd",
  "bamboo_mosaic_stairs": "Bamboo Mosaic Stairs",
  "birch_pressure_plate": "Birch Pressure Plate",
  "blue_concrete_powder": "Blue Concrete Powder",
  "experience_bottle": "Bottle o' Enchanting",
  "brain_coral_wall_fan": "Brain Coral Wall Fan",
  "brewer_pottery_sherd": "Brewer Pottery Sherd",
  "brown_mushroom_block": "Brown Mushroom Block",
  "pufferfish_bucket": "Bucket of Pufferfish",
  "red_candle_cake": "Cake with Red Candle",
  "chainmail_chestplate": "Chainmail Chestplate",
  "chiseled_tuff_bricks": "Chiseled Tuff Bricks",
  "cracked_stone_bricks": "Cracked Stone Bricks",
  "crimson_hanging_sign": "Crimson Hanging Sign",
  "cyan_concrete_powder": "Cyan Concrete Powder",
  "danger_pottery_sherd": "Danger Pottery Sherd",
  "dark_prismarine_slab": "Dark Prismarine Slab",
  "dead_brain_coral_fan": "Dead Brain Coral Fan",
  "deepslate_brick_slab": "Deepslate Brick Slab",
  "deepslate_brick_wall": "Deepslate Brick Wall",
  "deepslate_copper_ore": "Deepslate Copper Ore",
  "end_stone_brick_slab": "End Stone Brick Slab",
  "end_stone_brick_wall": "End Stone Brick Wall",
  "exposed_copper_grate": "Exposed Copper Grate",
  "fermented_spider_eye": "Fermented Spider Eye",
  "friend_pottery_sherd": "Friend Pottery Sherd",
  "glow_squid_spawn_egg": "Glow Squid Spawn Egg",
  "gray_concrete_powder": "Gray Concrete Powder",
  "guster_pottery_sherd": "Guster Pottery Sherd",
  "infested_cobblestone": "Infested Cobblestone",
  "iron_golem_spawn_egg": "Iron Golem Spawn Egg",
  "music_disc_pigstep": "Lena Raine - Pigstep",
  "lime_concrete_powder": "Lime Concrete Powder",
  "magma_cube_spawn_egg": "Magma Cube Spawn Egg",
  "hopper_minecart": "Minecart with Hopper",
  "muddy_mangrove_roots": "Muddy Mangrove Roots",
  "music_disc_precipice": "Music Disc Precipice",
  "netherite_chestplate": "Netherite Chestplate",
  "orange_wall_banner": "Orange Banner (Wall)",
  "orange_stained_glass": "Orange Stained Glass",
  "oxidized_copper_bulb": "Oxidized Copper Bulb",
  "oxidized_copper_door": "Oxidized Copper Door",
  "pink_concrete_powder": "Pink Concrete Powder",
  "plenty_pottery_sherd": "Plenty Pottery Sherd",
  "polar_bear_spawn_egg": "Polar Bear Spawn Egg",
  "polished_tuff_stairs": "Polished Tuff Stairs",
  "potted_birch_sapling": "Potted Birch Sapling",
  "potted_crimson_roots": "Potted Crimson Roots",
  "potted_warped_fungus": "Potted Warped Fungus",
  "powder_snow_cauldron": "Powder Snow Cauldron",
  "pufferfish_spawn_egg": "Pufferfish Spawn Egg",
  "purple_wall_banner": "Purple Banner (Wall)",
  "purple_stained_glass": "Purple Stained Glass",
  "red_sandstone_stairs": "Red Sandstone Stairs",
  "reinforced_deepslate": "Reinforced Deepslate",
  "scrape_pottery_sherd": "Scrape Pottery Sherd",
  "silverfish_spawn_egg": "Silverfish Spawn Egg",
  "smooth_quartz_stairs": "Smooth Quartz Stairs",
  "smooth_red_sandstone": "Smooth Red Sandstone",
  "snow_golem_spawn_egg": "Snow Golem Spawn Egg",
  "stone_pressure_plate": "Stone Pressure Plate",
  "stripped_acacia_wood": "Stripped Acacia Wood",
  "stripped_cherry_wood": "Stripped Cherry Wood",
  "stripped_jungle_wood": "Stripped Jungle Wood",
  "stripped_spruce_wood": "Stripped Spruce Wood",
  "stripped_warped_stem": "Stripped Warped Stem",
  "twisting_vines_plant": "Twisting Vines Plant",
  "vindicator_spawn_egg": "Vindicator Spawn Egg",
  "waxed_exposed_copper": "Waxed Exposed Copper",
  "weathered_cut_copper": "Weathered Cut Copper",
  "yellow_wall_banner": "Yellow Banner (Wall)",
  "yellow_stained_glass": "Yellow Stained Glass",
  "acacia_pressure_plate": "Acacia Pressure Plate",
  "arms_up_pottery_sherd": "Arms Up Pottery Sherd",
  "attached_pumpkin_stem": "Attached Pumpkin Stem",
  "bamboo_pressure_plate": "Bamboo Pressure Plate",
  "birch_chest_boat": "Birch Boat with Chest",
  "black_concrete_powder": "Black Concrete Powder",
  "lapis_block": "Block of Lapis Lazuli",
  "brown_concrete_powder": "Brown Concrete Powder",
  "bubble_coral_wall_fan": "Bubble Coral Wall Fan",
  "blue_candle_cake": "Cake with Blue Candle",
  "cyan_candle_cake": "Cake with Cyan Candle",
  "gray_candle_cake": "Cake with Gray Candle",
  "lime_candle_cake": "Cake with Lime Candle",
  "pink_candle_cake": "Cake with Pink Candle",
  "cave_spider_spawn_egg": "Cave Spider Spawn Egg",
  "cherry_pressure_plate": "Cherry Pressure Plate",
  "chiseled_quartz_block": "Chiseled Quartz Block",
  "chiseled_stone_bricks": "Chiseled Stone Bricks",
  "cracked_nether_bricks": "Cracked Nether Bricks",
  "dark_oak_hanging_sign": "Dark Oak Hanging Sign",
  "dead_bubble_coral_fan": "Dead Bubble Coral Fan",
  "dead_fire_coral_block": "Dead Fire Coral Block",
  "dead_horn_coral_block": "Dead Horn Coral Block",
  "dead_tube_coral_block": "Dead Tube Coral Block",
  "deepslate_diamond_ore": "Deepslate Diamond Ore",
  "deepslate_emerald_ore": "Deepslate Emerald Ore",
  "deepslate_tile_stairs": "Deepslate Tile Stairs",
  "green_concrete_powder": "Green Concrete Powder",
  "guster_banner_pattern": "Guster Banner Pattern",
  "infested_stone_bricks": "Infested Stone Bricks",
  "jungle_pressure_plate": "Jungle Pressure Plate",
  "light_blue_terracotta": "Light Blue Terracotta",
  "light_gray_terracotta": "Light Gray Terracotta",
  "magenta_wall_banner": "Magenta Banner (Wall)",
  "magenta_stained_glass": "Magenta Stained Glass",
  "mangrove_hanging_sign": "Mangrove Hanging Sign",
  "furnace_minecart": "Minecart with Furnace",
  "mourner_pottery_sherd": "Mourner Pottery Sherd",
  "oak_wall_hanging_sign": "Oak Wall Hanging Sign",
  "oxidized_copper_grate": "Oxidized Copper Grate",
  "pearlescent_froglight": "Pearlescent Froglight",
  "polished_diorite_slab": "Polished Diorite Slab",
  "polished_granite_slab": "Polished Granite Slab",
  "potted_acacia_sapling": "Potted Acacia Sapling",
  "potted_brown_mushroom": "Potted Brown Mushroom",
  "potted_cherry_sapling": "Potted Cherry Sapling",
  "potted_crimson_fungus": "Potted Crimson Fungus",
  "potted_jungle_sapling": "Potted Jungle Sapling",
  "potted_spruce_sapling": "Potted Spruce Sapling",
  "prismarine_brick_slab": "Prismarine Brick Slab",
  "red_glazed_terracotta": "Red Glazed Terracotta",
  "red_nether_brick_slab": "Red Nether Brick Slab",
  "red_nether_brick_wall": "Red Nether Brick Wall",
  "shelter_pottery_sherd": "Shelter Pottery Sherd",
  "smooth_sandstone_slab": "Smooth Sandstone Slab",
  "spruce_pressure_plate": "Spruce Pressure Plate",
  "stripped_crimson_stem": "Stripped Crimson Stem",
  "stripped_dark_oak_log": "Stripped Dark Oak Log",
  "stripped_mangrove_log": "Stripped Mangrove Log",
  "warped_pressure_plate": "Warped Pressure Plate",
  "waxed_copper_block": "Waxed Block of Copper",
  "waxed_chiseled_copper": "Waxed Chiseled Copper",
  "waxed_copper_trapdoor": "Waxed Copper Trapdoor",
  "waxed_cut_copper_slab": "Waxed Cut Copper Slab",
  "waxed_oxidized_copper": "Waxed Oxidized Copper",
  "weathered_copper_bulb": "Weathered Copper Bulb",
  "weathered_copper_door": "Weathered Copper Door",
  "white_concrete_powder": "White Concrete Powder",
  "wither_skeleton_skull": "Wither Skeleton Skull",
  "acacia_chest_boat": "Acacia Boat with Chest",
  "bamboo_chest_raft": "Bamboo Raft with Chest",
  "blue_glazed_terracotta": "Blue Glazed Terracotta",
  "black_candle_cake": "Cake with Black Candle",
  "brown_candle_cake": "Cake with Brown Candle",
  "green_candle_cake": "Cake with Green Candle",
  "white_candle_cake": "Cake with White Candle",
  "cherry_chest_boat": "Cherry Boat with Chest",
  "chiseled_nether_bricks": "Chiseled Nether Bricks",
  "chiseled_red_sandstone": "Chiseled Red Sandstone",
  "cobbled_deepslate_slab": "Cobbled Deepslate Slab",
  "cobbled_deepslate_wall": "Cobbled Deepslate Wall",
  "crimson_pressure_plate": "Crimson Pressure Plate",
  "cut_red_sandstone_slab": "Cut Red Sandstone Slab",
  "cyan_glazed_terracotta": "Cyan Glazed Terracotta",
  "dark_prismarine_stairs": "Dark Prismarine Stairs",
  "dead_brain_coral_block": "Dead Brain Coral Block",
  "deepslate_brick_stairs": "Deepslate Brick Stairs",
  "deepslate_redstone_ore": "Deepslate Redstone Ore",
  "enchanted_golden_apple": "Enchanted Golden Apple",
  "end_stone_brick_stairs": "End Stone Brick Stairs",
  "ender_dragon_spawn_egg": "Ender Dragon Spawn Egg",
  "explorer_pottery_sherd": "Explorer Pottery Sherd",
  "glistering_melon_slice": "Glistering Melon Slice",
  "gray_glazed_terracotta": "Gray Glazed Terracotta",
  "jungle_chest_boat": "Jungle Boat with Chest",
  "music_disc_otherside": "Lena Raine - otherside",
  "light_blue_shulker_box": "Light Blue Shulker Box",
  "light_gray_shulker_box": "Light Gray Shulker Box",
  "lime_glazed_terracotta": "Lime Glazed Terracotta",
  "mossy_cobblestone_slab": "Mossy Cobblestone Slab",
  "mossy_cobblestone_wall": "Mossy Cobblestone Wall",
  "mossy_stone_brick_slab": "Mossy Stone Brick Slab",
  "mossy_stone_brick_wall": "Mossy Stone Brick Wall",
  "orange_concrete_powder": "Orange Concrete Powder",
  "piglin_brute_spawn_egg": "Piglin Brute Spawn Egg",
  "pink_glazed_terracotta": "Pink Glazed Terracotta",
  "polished_andesite_slab": "Polished Andesite Slab",
  "purple_concrete_powder": "Purple Concrete Powder",
  "red_stained_glass_pane": "Red Stained Glass Pane",
  "spruce_chest_boat": "Spruce Boat with Chest",
  "stripped_dark_oak_wood": "Stripped Dark Oak Wood",
  "stripped_mangrove_wood": "Stripped Mangrove Wood",
  "stripped_warped_hyphae": "Stripped Warped Hyphae",
  "trader_llama_spawn_egg": "Trader Llama Spawn Egg",
  "waxed_weathered_copper": "Waxed Weathered Copper",
  "weathered_copper_grate": "Weathered Copper Grate",
  "yellow_concrete_powder": "Yellow Concrete Powder",
  "zombie_horse_spawn_egg": "Zombie Horse Spawn Egg",
  "birch_wall_hanging_sign": "Birch Wall Hanging Sign",
  "black_glazed_terracotta": "Black Glazed Terracotta",
  "blue_stained_glass_pane": "Blue Stained Glass Pane",
  "brown_glazed_terracotta": "Brown Glazed Terracotta",
  "tropical_fish_bucket": "Bucket of Tropical Fish",
  "orange_candle_cake": "Cake with Orange Candle",
  "purple_candle_cake": "Cake with Purple Candle",
  "yellow_candle_cake": "Cake with Yellow Candle",
  "calibrated_sculk_sensor": "Calibrated Sculk Sensor",
  "cracked_deepslate_tiles": "Cracked Deepslate Tiles",
  "cyan_stained_glass_pane": "Cyan Stained Glass Pane",
  "dark_oak_pressure_plate": "Dark Oak Pressure Plate",
  "dead_bubble_coral_block": "Dead Bubble Coral Block",
  "exposed_chiseled_copper": "Exposed Chiseled Copper",
  "exposed_copper_trapdoor": "Exposed Copper Trapdoor",
  "exposed_cut_copper_slab": "Exposed Cut Copper Slab",
  "flowering_azalea_leaves": "Flowering Azalea Leaves",
  "gray_stained_glass_pane": "Gray Stained Glass Pane",
  "green_glazed_terracotta": "Green Glazed Terracotta",
  "lime_stained_glass_pane": "Lime Stained Glass Pane",
  "magenta_concrete_powder": "Magenta Concrete Powder",
  "mangrove_pressure_plate": "Mangrove Pressure Plate",
  "pink_stained_glass_pane": "Pink Stained Glass Pane",
  "polished_deepslate_slab": "Polished Deepslate Slab",
  "polished_deepslate_wall": "Polished Deepslate Wall",
  "polished_diorite_stairs": "Polished Diorite Stairs",
  "polished_granite_stairs": "Polished Granite Stairs",
  "potted_dark_oak_sapling": "Potted Dark Oak Sapling",
  "potted_flowering_azalea_bush": "Potted Flowering Azalea",
  "prismarine_brick_stairs": "Prismarine Brick Stairs",
  "red_nether_brick_stairs": "Red Nether Brick Stairs",
  "repeating_command_block": "Repeating Command Block",
  "smooth_sandstone_stairs": "Smooth Sandstone Stairs",
  "stripped_crimson_hyphae": "Stripped Crimson Hyphae",
  "tropical_fish_spawn_egg": "Tropical Fish Spawn Egg",
  "waxed_cut_copper_stairs": "Waxed Cut Copper Stairs",
  "white_glazed_terracotta": "White Glazed Terracotta",
  "acacia_wall_hanging_sign": "Acacia Wall Hanging Sign",
  "bamboo_wall_hanging_sign": "Bamboo Wall Hanging Sign",
  "black_stained_glass_pane": "Black Stained Glass Pane",
  "stripped_bamboo_block": "Block of Stripped Bamboo",
  "brown_stained_glass_pane": "Brown Stained Glass Pane",
  "magenta_candle_cake": "Cake with Magenta Candle",
  "cherry_wall_hanging_sign": "Cherry Wall Hanging Sign",
  "cobbled_deepslate_stairs": "Cobbled Deepslate Stairs",
  "cracked_deepslate_bricks": "Cracked Deepslate Bricks",
  "dark_oak_chest_boat": "Dark Oak Boat with Chest",
  "dead_fire_coral_wall_fan": "Dead Fire Coral Wall Fan",
  "dead_horn_coral_wall_fan": "Dead Horn Coral Wall Fan",
  "dead_tube_coral_wall_fan": "Dead Tube Coral Wall Fan",
  "elder_guardian_spawn_egg": "Elder Guardian Spawn Egg",
  "green_stained_glass_pane": "Green Stained Glass Pane",
  "heartbreak_pottery_sherd": "Heartbreak Pottery Sherd",
  "jungle_wall_hanging_sign": "Jungle Wall Hanging Sign",
  "light_blue_wall_banner": "Light Blue Banner (Wall)",
  "light_blue_stained_glass": "Light Blue Stained Glass",
  "light_gray_wall_banner": "Light Gray Banner (Wall)",
  "light_gray_stained_glass": "Light Gray Stained Glass",
  "mangrove_chest_boat": "Mangrove Boat with Chest",
  "mossy_cobblestone_stairs": "Mossy Cobblestone Stairs",
  "mossy_stone_brick_stairs": "Mossy Stone Brick Stairs",
  "orange_glazed_terracotta": "Orange Glazed Terracotta",
  "oxidized_chiseled_copper": "Oxidized Chiseled Copper",
  "oxidized_copper_trapdoor": "Oxidized Copper Trapdoor",
  "oxidized_cut_copper_slab": "Oxidized Cut Copper Slab",
  "polished_andesite_stairs": "Polished Andesite Stairs",
  "polished_blackstone_slab": "Polished Blackstone Slab",
  "polished_blackstone_wall": "Polished Blackstone Wall",
  "purple_glazed_terracotta": "Purple Glazed Terracotta",
  "skeleton_horse_spawn_egg": "Skeleton Horse Spawn Egg",
  "spruce_wall_hanging_sign": "Spruce Wall Hanging Sign",
  "warped_fungus_on_a_stick": "Warped Fungus on a Stick",
  "warped_wall_hanging_sign": "Warped Wall Hanging Sign",
  "waxed_exposed_cut_copper": "Waxed Exposed Cut Copper",
  "white_stained_glass_pane": "White Stained Glass Pane",
  "yellow_glazed_terracotta": "Yellow Glazed Terracotta",
  "crimson_wall_hanging_sign": "Crimson Wall Hanging Sign",
  "dead_brain_coral_wall_fan": "Dead Brain Coral Wall Fan",
  "exposed_cut_copper_stairs": "Exposed Cut Copper Stairs",
  "magenta_glazed_terracotta": "Magenta Glazed Terracotta",
  "orange_stained_glass_pane": "Orange Stained Glass Pane",
  "polished_deepslate_stairs": "Polished Deepslate Stairs",
  "potted_mangrove_propagule": "Potted Mangrove Propagule",
  "purple_stained_glass_pane": "Purple Stained Glass Pane",
  "smooth_red_sandstone_slab": "Smooth Red Sandstone Slab",
  "waxed_exposed_copper_bulb": "Waxed Exposed Copper Bulb",
  "waxed_exposed_copper_door": "Waxed Exposed Copper Door",
  "waxed_oxidized_cut_copper": "Waxed Oxidized Cut Copper",
  "weathered_chiseled_copper": "Weathered Chiseled Copper",
  "weathered_copper_trapdoor": "Weathered Copper Trapdoor",
  "weathered_cut_copper_slab": "Weathered Cut Copper Slab",
  "wither_skeleton_spawn_egg": "Wither Skeleton Spawn Egg",
  "yellow_stained_glass_pane": "Yellow Stained Glass Pane",
  "zombie_villager_spawn_egg": "Zombie Villager Spawn Egg",
  "dark_oak_wall_hanging_sign": "Dark Oak Wall Hanging Sign",
  "dead_bubble_coral_wall_fan": "Dead Bubble Coral Wall Fan",
  "deepslate_lapis_ore": "Deepslate Lapis Lazuli Ore",
  "light_blue_concrete_powder": "Light Blue Concrete Powder",
  "light_gray_concrete_powder": "Light Gray Concrete Powder",
  "magenta_stained_glass_pane": "Magenta Stained Glass Pane",
  "mangrove_wall_hanging_sign": "Mangrove Wall Hanging Sign",
  "oxidized_cut_copper_stairs": "Oxidized Cut Copper Stairs",
  "polished_blackstone_bricks": "Polished Blackstone Bricks",
  "polished_blackstone_button": "Polished Blackstone Button",
  "polished_blackstone_stairs": "Polished Blackstone Stairs",
  "wandering_trader_spawn_egg": "Wandering Trader Spawn Egg",
  "waxed_exposed_copper_grate": "Waxed Exposed Copper Grate",
  "waxed_oxidized_copper_bulb": "Waxed Oxidized Copper Bulb",
  "waxed_oxidized_copper_door": "Waxed Oxidized Copper Door",
  "waxed_weathered_cut_copper": "Waxed Weathered Cut Copper",
  "wither_skeleton_wall_skull": "Wither Skeleton Wall Skull",
  "zombified_piglin_spawn_egg": "Zombified Piglin Spawn Egg",
  "light_blue_candle_cake": "Cake with Light Blue Candle",
  "light_gray_candle_cake": "Cake with Light Gray Candle",
  "infested_mossy_stone_bricks": "Infested Mossy Stone Bricks",
  "command_block_minecart": "Minecart with Command Block",
  "smooth_red_sandstone_stairs": "Smooth Red Sandstone Stairs",
  "waxed_oxidized_copper_grate": "Waxed Oxidized Copper Grate",
  "waxed_weathered_copper_bulb": "Waxed Weathered Copper Bulb",
  "waxed_weathered_copper_door": "Waxed Weathered Copper Door",
  "weathered_cut_copper_stairs": "Weathered Cut Copper Stairs",
  "chiseled_polished_blackstone": "Chiseled Polished Blackstone",
  "light_blue_glazed_terracotta": "Light Blue Glazed Terracotta",
  "light_gray_glazed_terracotta": "Light Gray Glazed Terracotta",
  "music_disc_creator_music_box": "Music Disc Creator Music Box",
  "waxed_weathered_copper_grate": "Waxed Weathered Copper Grate",
  "heavy_weighted_pressure_plate": "Heavy Weighted Pressure Plate",
  "infested_cracked_stone_bricks": "Infested Cracked Stone Bricks",
  "light_blue_stained_glass_pane": "Light Blue Stained Glass Pane",
  "light_gray_stained_glass_pane": "Light Gray Stained Glass Pane",
  "light_weighted_pressure_plate": "Light Weighted Pressure Plate",
  "waxed_exposed_chiseled_copper": "Waxed Exposed Chiseled Copper",
  "waxed_exposed_copper_trapdoor": "Waxed Exposed Copper Trapdoor",
  "waxed_exposed_cut_copper_slab": "Waxed Exposed Cut Copper Slab",
  "infested_chiseled_stone_bricks": "Infested Chiseled Stone Bricks",
  "polished_blackstone_brick_slab": "Polished Blackstone Brick Slab",
  "polished_blackstone_brick_wall": "Polished Blackstone Brick Wall",
  "waxed_oxidized_chiseled_copper": "Waxed Oxidized Chiseled Copper",
  "waxed_oxidized_copper_trapdoor": "Waxed Oxidized Copper Trapdoor",
  "waxed_oxidized_cut_copper_slab": "Waxed Oxidized Cut Copper Slab",
  "waxed_exposed_cut_copper_stairs": "Waxed Exposed Cut Copper Stairs",
  "waxed_weathered_chiseled_copper": "Waxed Weathered Chiseled Copper",
  "waxed_weathered_copper_trapdoor": "Waxed Weathered Copper Trapdoor",
  "waxed_weathered_cut_copper_slab": "Waxed Weathered Cut Copper Slab",
  "eye_armor_trim_smithing_template": "Eye Armor Trim Smithing Template",
  "polished_blackstone_brick_stairs": "Polished Blackstone Brick Stairs",
  "rib_armor_trim_smithing_template": "Rib Armor Trim Smithing Template",
  "vex_armor_trim_smithing_template": "Vex Armor Trim Smithing Template",
  "waxed_oxidized_cut_copper_stairs": "Waxed Oxidized Cut Copper Stairs",
  "bolt_armor_trim_smithing_template": "Bolt Armor Trim Smithing Template",
  "dune_armor_trim_smithing_template": "Dune Armor Trim Smithing Template",
  "flow_armor_trim_smithing_template": "Flow Armor Trim Smithing Template",
  "host_armor_trim_smithing_template": "Host Armor Trim Smithing Template",
  "tide_armor_trim_smithing_template": "Tide Armor Trim Smithing Template",
  "ward_armor_trim_smithing_template": "Ward Armor Trim Smithing Template",
  "waxed_weathered_cut_copper_stairs": "Waxed Weathered Cut Copper Stairs",
  "wild_armor_trim_smithing_template": "Wild Armor Trim Smithing Template",
  "coast_armor_trim_smithing_template": "Coast Armor Trim Smithing Template",
  "cracked_polished_blackstone_bricks": "Cracked Polished Blackstone Bricks",
  "polished_blackstone_pressure_plate": "Polished Blackstone Pressure Plate",
  "snout_armor_trim_smithing_template": "Snout Armor Trim Smithing Template",
  "spire_armor_trim_smithing_template": "Spire Armor Trim Smithing Template",
  "netherite_upgrade_smithing_template": "Netherite Upgrade Smithing Template",
  "raiser_armor_trim_smithing_template": "Raiser Armor Trim Smithing Template",
  "sentry_armor_trim_smithing_template": "Sentry Armor Trim Smithing Template",
  "shaper_armor_trim_smithing_template": "Shaper Armor Trim Smithing Template",
  "silence_armor_trim_smithing_template": "Silence Armor Trim Smithing Template",
  "wayfinder_armor_trim_smithing_template": "Wayfinder Armor Trim Smithing Template"
};